apiVersion: v2
name: openbalena
description: openBalena kubernetes Chart
type: application
version: 1.2.0
appVersion: v3.6.0
keywords:
- balena
- openbalena
maintainers:
- name: bartversluijs
  email: bartv@nexelit.io

dependencies:
- name: haproxy-ingress
  version: 0.13.6
  alias: haproxy
  repository: "https://haproxy-ingress.github.io/charts"

