apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: registry
  name: openbalena-registry
spec:
  serviceName: openbalena-registry
  replicas: {{ index .Values "deployments" "registry" "replicas" }}
  selector:
    matchLabels:
      app: openbalena
      component: registry
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openbalena
        component: registry
    spec:
      containers:
      - image: '{{ index .Values "deployments" "registry" "image" }}:{{ index .Values "deployments" "registry" "version" }}'
        name: openbalena-registry
        resources: {}
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_RESOURCE
        env:
        - name: CONFD_BACKEND
          value: "ENV"
        - name: API_TOKENAUTH_CRT
          value: "{{ index .Values "keys" "token-auth-pub" }}"
        - name: BALENA_REGISTRY2_HOST
          value: "registry.{{ index .Values "hostname" }}"
        - name: BALENA_ROOT_CA
          value: "{{ index .Values "certificates" "root" "ca" }}"
        - name: BALENA_TOKEN_AUTH_ISSUER
          value: "api.{{ index .Values "hostname" }}"
        - name: BALENA_TOKEN_AUTH_REALM
          value: "https://api.{{ index .Values "hostname" }}/auth/v1/token"
        - name: COMMON_REGION
          value: "{{ index .Values "config" "s3" "region" }}"
        - name: REGISTRY2_CACHE_ENABLED
          value: "false"
        - name: REGISTRY2_CACHE_ADDR
          value: "127.0.0.1:6379"
        - name: REGISTRY2_CACHE_DB
          value: "0"
        - name: REGISTRY2_CACHE_MAXMEMORY_MB
          value: "1024" # Megabytes
        - name: REGISTRY2_CACHE_MAXMEMORY_POLICY
          value: "allkeys-lru"
        - name: REGISTRY2_S3_REGION_ENDPOINT
          value: "{{ index .Values "config" "s3" "endpoint" }}"
        - name: REGISTRY2_S3_BUCKET
          value: "{{ index .Values "config" "s3" "bucket" }}"
        - name: REGISTRY2_S3_KEY
          value: "{{ index .Values "config" "s3" "access-key" }}"
        - name: REGISTRY2_S3_SECRET
          value: "{{ index .Values "config" "s3" "secret-key" }}"
        - name: REGISTRY2_SECRETKEY
          value: "{{ index .Values "keys" "registry-secret-key" }}"
        - name: REGISTRY2_STORAGEPATH
          value: "/data"
        volumeMounts:
        - mountPath: /data
          name: openbalena-registry-volume
          subPath: registry
        - mountPath: /run
          name: openbalena-registry-tmpfs0
        - mountPath: /sys/fs/cgroup
          name: openbalena-registry-tmpfs1
      volumes:
      - name: openbalena-registry-volume
        persistentVolumeClaim:
          claimName: openbalena-registry-volume
      - name: openbalena-registry-tmpfs0
        emptyDir:
          medium: Memory
      - name: openbalena-registry-tmpfs1
        emptyDir:
          medium: Memory

      nodeSelector:
        {{- toYaml .Values.deployments.registry.nodeSelector | nindent 8 }}
  volumeClaimTemplates:
  - metadata:
      name: openbalena-registry-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ index .Values "deployments" "registry" "volume" "storage" }}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: registry
  name: openbalena-registry
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: openbalena
    component: registry
status:
  loadBalancer: {}
