{{- if index .Values "deployments" "redis" "enabled" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: openbalena-redis-volume
  labels:
    app: openbalena
    component: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ index .Values "deployments" "redis" "volume" "storage" }}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: redis
  name: openbalena-redis
spec:
  replicas: {{ index .Values "deployments" "redis" "replicas" }}
  selector:
    matchLabels:
      app: openbalena
      component: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openbalena
        component: redis
    spec:
      containers:
      - image: {{ index .Values "deployments" "redis" "image" }}:{{ index .Values "deployments" "redis" "version" }}
        name: openbalena-redis
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: openbalena-redis-volume
          subPath: redis
      volumes:
      - name: openbalena-redis-volume
        persistentVolumeClaim:
          claimName: volume-redis
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: openbalena
    component: redis
  name: openbalena-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: {{ index .Values "deployments" "redis" "config" "port" }}
  selector:
    app: openbalena-redis
status:
  loadBalancer: {}
{{- end }}
