apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openbalena.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: db

    {{- with .Values.db.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.db.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceName: {{ include "openbalena.fullname" . }}-db
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: db

      {{- with .Values.db.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  replicas: {{ .Values.db.replicas }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db

        {{- with .Values.db.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-db
        image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        {{- with .Values.db.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - name: postgres
            containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
          subPath: postgres
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data

      {{- with .Values.db.nodeSelector  }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.db.storageClass }}
      storageClassName: {{ .Values.db.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.db.storage }}
