apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbalena.fullname" . }}-vpn
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: vpn

    {{- with .Values.vpn.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.vpn.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.vpn.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.vpn.replicas  }}
  replicas: {{ .Values.vpn.replicas }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vpn

      {{- with .Values.vpn.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vpn

        {{- with .Values.vpn.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ .Values.vpn.hostNetwork }}
      containers:
      - name: {{ .Chart.Name }}-api
        image: {{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag }}
        imagePullPolicy: {{ .Values.vpn.image.pullPolicy }}
        {{- with .Values.vpn.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: vpn
          containerPort: 443
          hostPort: 443
        - name: tunnel
          containerPort: 3128
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE", "NET_ADMIN"]
        env:
        - name: CONFD_BACKEND
          value: "ENV"
        - name: API_SERVICE_API_KEY
          value: "{{ index .Values "global" "keys" "api-vpn-service-api-key" }}"
        - name: BALENA_API_HOST
          value: "api.{{ .Values.global.hostname }}"
        - name: BALENA_ROOT_CA
          value: "{{ index .Values "global" "certificates" "root" "ca" }}"
        - name: BALENA_VPN_PORT
          value: "443"
        - name: PRODUCTION_MODE
          value: "{{ index .Values "global" "production-mode" }}"
        - name: RESIN_VPN_GATEWAY
          value: "10.2.0.1"
        - name: SENTRY_DSN
          value: "{{ index .Values "vpn" "sentry-dsn" }}"
        - name: VPN_HAPROXY_USEPROXYPROTOCOL
          value: "true"
        - name: VPN_OPENVPN_CA_CRT
          value: "{{ index .Values "global" "certificates" "vpn" "ca" }}"
        - name: VPN_OPENVPN_SERVER_CRT
          value: "{{ index .Values "global" "certificates" "vpn" "crt" }}"
        - name: VPN_OPENVPN_SERVER_DH
          value: "{{ index .Values "global" "certificates" "vpn" "dh" }}"
        - name: VPN_OPENVPN_SERVER_KEY
          value: "{{ index .Values "global" "certificates" "vpn" "server-key" }}"
        - name: VPN_SERVICE_API_KEY
          value: "{{ index .Values "global" "keys" "service-api-key" }}"
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: run
        emptyDir:
          medium: Memory
      - name: cgroup
        emptyDir:
          medium: Memory

      {{- with .Values.vpn.nodeSelector  }}
      nodeSelector:
        {{- toYaml .Values.vpn.nodeSelector | nindent 8 }}
      {{- end }}
